### ISSUE TITLE
can't compile on beta 5.6.0f1

### ISSUE THREAD

**Issue by ConradBrean** [Unity-Technologies/ScriptableRenderLoop#199]
I have the following compilation errors with 5.6.0f1: 

Assets/ScriptableRenderPipeline/HDRenderPipeline/HDRenderPipeline.cs(648,53): error CS0117: `UnityEngine.CameraType' does not contain a definition for `Reflection'

Assets/ScriptableRenderPipeline/HDRenderPipeline/Lighting/TilePass/TilePass.cs(1162,52): error CS0117: `UnityEngine.CameraType' does not contain a definition for `Reflection'

Assets/ScriptableRenderPipeline/HDRenderPipeline/Material/Lit/SubsurfaceScatteringProfile.cs(488,55): error CS0122: `UnityEngine.Experimental.Rendering.RenderPipelineManager' is inaccessible due to its protection level

Assets/ScriptableRenderPipeline/HDRenderPipeline/Material/Lit/SubsurfaceScatteringProfile.cs(488,77): error CS0122: `UnityEngine.Experimental.Rendering.RenderPipelineManager.currentPipeline.get' is inaccessible due to its protection level

Assets/ScriptableRenderPipeline/common/TextureCache.cs(136,21): error CS0117: `UnityEngine.Texture2DArray' does not contain a definition for `wrapModeV'

So, my question is: what version of unity should i download to play with this, if any?

**Comment by JacobSmaga** [comment]
This https://github.com/Unity-Technologies/ScriptableRenderLoop/releases/tag/unity-5.6.0b10 with 5.6.0b10 https://unity3d.com/unity/beta/archive

**Comment by ConradBrean** [comment]
Thanks, but it doesn't work either. I see white screen instead of gui when unity imports all the assets, and then it crashes.

**Comment by JacobSmaga** [comment]
Do you have this problem when you open any other project with 5.6.0b10?

**Comment by ConradBrean** [comment]
No, I don't.

**Comment by sebastienlagarde** [comment]
Hi,
HDRenderpipeline can't be use with public version yet, sorry. This project is in development and will change a lot. We provide read access just to give an insight of what may happen in the future, it is expected that it is in unstable state and don't run with public version :). Thanks.

Seb
