### ISSUE TITLE
Tagged versions don't compile with 2017.1 and 2017.2.0b4

### ISSUE THREAD

**Issue by pauliusuza** [Unity-Technologies/ScriptableRenderLoop#349]
Followed instructions (git checkout, submodule update)
Getting a few errors:

```
Assets/ScriptableRenderPipeline/HDRenderPipeline/HDRenderPipeline.cs(5,32): error CS0234: The type or namespace name `PostProcessing' does not exist in the namespace `UnityEngine.Experimental'. Are you missing an assembly reference?

Assets/ScriptableRenderPipeline/HDRenderPipeline/HDRenderPipelineAsset.cs(4,32): error CS0234: The type or namespace name `PostProcessing' does not exist in the namespace `UnityEngine.Experimental'. Are you missing an assembly reference?

Assets/ScriptableRenderPipeline/HDRenderPipeline/HDRenderPipeline.cs(120,18): error CS0246: The type or namespace name `PostProcessRenderContext' could not be found. Are you missing `UnityEngine.Rendering.PostProcessing' using directive?
```

Also it seems the PostProcessing framework is not included or is under wrong namespace (Experimental), is there a missing submodule / separate download?

**Comment by sebastienlagarde** [comment]
Hey, It mean you haven't the correct postprocess version which is in a submodule.
have you try git submodule update --init --recursive  (on Postprocess submodule) ?

Else it may mean that we haven't tagged correctly the postprocess version and you may have a too recent version of postprocess that is not compatible with this (old) version of github project

**Comment by pauliusuza** [comment]
git submodule update --init --recursive did not work at first from the root of the project, but it seems it worked when I ran it inside the PostProcess folder, thanks

**Comment by DevJoseWeb** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'PostProcessing' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)	Assembly-CSharp	C:\Users\web2a\OneDrive\3DKit\Assets\3DGamekit\Scripts\Game\Utility\QualitySettingPostprocessProfileSwitch.cs	4	Active
